language: node_js
node_js:
- 8
cache:
  directories:
  - node_modules
install:
- npm install
script:
- npm run lint
- npm run build
after_success:
- openssl aes-256-cbc -K $encrypted_ddbeb015644f_key -iv $encrypted_ddbeb015644f_iv 
-in ./.travis/key.enc -out ./.travis/key -d
- chmod 600 .travis/key
- eval "$(ssh-agent -s)"
- ssh-add .travis/key
- scp -o stricthostkeychecking=no -r ./build $DEPLOY_USER@$DEPLOY_HOST:$DEPLOY_PATH;
- ssh -o stricthostkeychecking=no $DEPLOY_USER@$DEPLOY_HOST "./deploy_web.sh";